### PR TITLE
Adding html directory for website_B

### PR DESCRIPTION
**Pull request by ashwinimarathe**
- We have introduced a new section called _Learning paths_ just below _Class Schedule_ in the sidebar
- We created an a new directory called html_B at ./docs/html/ for the change
- Since all the webpages had the code for the sidebar, we had to touch all the HTML files and make the required change

### CODE REVIEW

**Comment by nickeubank** [comment]
Three notes: 

- There's an `index.html` file in `docs` that is the "master" file for github pages. Right now it's designed to redirect to `docs/html/index.html`. Not sure how that affects traffic routing. 
- You'll need to delete all HTML pages and rebuilt to get the menu to rebuild, otherwise the "learning path" will appear and disappear:

image

- You may want to add a note about the "learning paths" at the bottom of all exercises (say, "want more exercises? Check out a list of all available exercises here!") to improve findability.

**Comment by ashwinimarathe** [comment]
- The `index.html` file in `docs` will redirect to `/html/index.html`, so we plan to use `html/index.html` as the original page and `html_b/index.html` as the variant, so that anytime someone hits `html/index.html` half the time they will be redirected to  `html_b/index.html`.
- Will do that and push again

**Comment by nickeubank** [comment]
Great!

**Comment by nickeubank** [comment]
Looks good! I'll merge now so you can start playing with Optimize, but feel free to submit more PRs if you want more edits.

**Comment by ashwinimarathe** [comment]
- Updated the sidebar for exercise pages to display the `Learning Tracks` link

**Pull request merged**
